[platformio]
default_envs = esp32s2_4mb
data_dir = data_svelte

[common_env_data]
lib_deps_external = 
	bblanchon/ArduinoJson @6.18.0
	knolleary/PubSubClient

[env]
extra_scripts = pre:tools/prebuildscript.py

[env:esp8266_1mb_ota]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_1mb_ota_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_1mb_ota="esp8266_1mb_ota"
	${env:esp8266_1mb_ota_fromitems.build_flags}
framework = arduino
board = nodemcuv2
board_build.ldscript = eagle.flash.1m64.ld
platform = espressif8266 @4.0.1
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_1mb_ota_fromitems.build_src_filter}

[env:esp8266_1mb]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_1mb_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_1mb="esp8266_1mb"
	${env:esp8266_1mb_fromitems.build_flags}
framework = arduino
board = nodemcuv2
board_build.ldscript = eagle.flash.1m256.ld
platform = espressif8266 @4.0.1
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_1mb_fromitems.build_src_filter}

[env:esp8285_1mb_ota]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8285_1mb_ota_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_1mb_ota="esp8266_1mb_ota"
	${env:esp8285_1mb_ota_fromitems.build_flags}
framework = arduino
board = esp8285
board_build.ldscript = eagle.flash.1m64.ld
platform = espressif8266 @4.0.1
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8285_1mb_ota_fromitems.build_src_filter}

[env:esp8266_2mb]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_2mb_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_2mb="esp8266_2mb"
	${env:esp8266_2mb_fromitems.build_flags}
framework = arduino
board = d1_wroom_02
board_build.ldscript = eagle.flash.2m1m.ld
platform = espressif8266 @4.2.0
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_2mb_fromitems.build_src_filter}

[env:esp8266_2mb_ota]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_2mb_ota_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_2mb_ota="esp8266_2mb_ota"
	${env:esp8266_2mb_ota_fromitems.build_flags}
framework = arduino
board = d1_wroom_02
board_build.ldscript = eagle.flash.2m256.ld
platform = espressif8266 @4.2.0
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_2mb_ota_fromitems.build_src_filter}

[env:esp8285_1mb]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8285_1mb_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_1mb="esp8266_1mb"
	${env:esp8285_1mb_fromitems.build_flags}
framework = arduino
board = esp8285
board_build.ldscript = eagle.flash.1m256.ld
platform = espressif8266 @4.0.1
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8285_1mb_fromitems.build_src_filter}

[env:esp8266_4mb]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_4mb_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_4mb="esp8266_4mb"
	${env:esp8266_4mb_fromitems.build_flags}
framework = arduino
board = nodemcuv2
board_build.ldscript = eagle.flash.4m2m.ld
platform = espressif8266 @4.0.1
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_4mb_fromitems.build_src_filter}

[env:esp8266_16mb]
extra_scripts = pre:tools/patch8266_16m.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp8266_16mb_fromitems.lib_deps}
	ESPAsyncUDP
lib_ignore = LT_WebSockets
build_flags = 
	-Desp8266_16mb="esp8266_16mb"
	${env:esp8266_16mb_fromitems.build_flags}
framework = arduino
board = nodemcuv2
platform = espressif8266 @4.0.1
board_build.ldscript = eagle.flash.16m14m.ld
monitor_filters = esp8266_exception_decoder
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp8266_16mb_fromitems.build_src_filter}

[env:esp32_4mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32_4mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32_4mb="esp32_4mb"
	-Wl,--wrap=esp_panic_handler
	${env:esp32_4mb_fromitems.build_flags}
framework = arduino
board = esp32dev
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32_4mb_fromitems.build_src_filter}

[env:esp32_4mb3f]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32_4mb3f_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32_4mb3f="esp32_4mb3f"
	-Wl,--wrap=esp_panic_handler
	${env:esp32_4mb3f_fromitems.build_flags}
framework = arduino
board = esp32dev
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/partitions_custom.csv
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32_4mb3f_fromitems.build_src_filter}

[env:esp32cam_4mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32cam_4mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32cam_4mb="esp32cam_4mb"
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-Wl,--wrap=esp_panic_handler
	${env:esp32cam_4mb_fromitems.build_flags}
framework = arduino
board = esp32cam
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32cam_4mb_fromitems.build_src_filter}

[env:esp32s2_4mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32s2_4mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32s2_4mb="esp32s2_4mb"
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-Wl,--wrap=esp_panic_handler
	${env:esp32s2_4mb_fromitems.build_flags}
framework = arduino
board = lolin_s2_mini
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32s2_4mb_fromitems.build_src_filter}

[env:esp32c3m_4mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32c3m_4mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32c3m_4mb="esp32c3m_4mb"
	-Wl,--wrap=esp_panic_handler
	${env:esp32c3m_4mb_fromitems.build_flags}
framework = arduino
board = lolin_c3_mini
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.filesystem = littlefs
board_build.partitions = tools/partitions_custom.csv
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32c3m_4mb_fromitems.build_src_filter}

[env:esp32s3_16mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32s3_16mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32s3_16mb="esp32s3_16mb"
	-Wl,--wrap=esp_panic_handler
	${env:esp32s3_16mb_fromitems.build_flags}
framework = arduino
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32s3_16mb_fromitems.build_src_filter}

[env:esp32_16mb]
extra_scripts = pre:tools/patch32_ws.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32_16mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32_16mb="esp32_16mb"
	-Wl,--wrap=esp_panic_handler
	${env:esp32_16mb_fromitems.build_flags}
framework = arduino
board = esp32dev
platform = espressif32 @6.6.0
monitor_filters = esp32_exception_decoder
upload_port = COM11
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/large_spiffs_16MB.csv
board_upload.flash_size = 16MB
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32_16mb_fromitems.build_src_filter}

[env:esp32_wifirep]
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32_wifirep_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32_wifirep="esp32_wifirep"
	-Wl,--wrap=esp_panic_handler
	${env:esp32_wifirep_fromitems.build_flags}
framework = arduino
board = esp32dev
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.5.3/platform-espressif32-2.0.5.3.zip
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/partitions_custom.csv
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32_wifirep_fromitems.build_src_filter}

[env:esp32c6_4mb]
extra_scripts = pre:tools/patch32c6.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32c6_4mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32c6_4mb="esp32c6_4mb"
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=0
	-Wl,--wrap=esp_panic_handler
	${env:esp32c6_4mb_fromitems.build_flags}
framework = arduino
board = esp32-c6-devkitm-1
platform = espressif32 @6.9.0
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/partitions_custom.csv
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32c6_4mb_fromitems.build_src_filter}

[env:esp32c6_8mb]
extra_scripts = pre:tools/patch32c6.py
lib_deps = 
	${common_env_data.lib_deps_external}
	${env:esp32c6_8mb_fromitems.lib_deps}
lib_ignore = LT_WebSockets
build_flags = 
	-Desp32c6_8mb="esp32c6_8mb"
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MODE=0
	-Wl,--wrap=esp_panic_handler
	${env:esp32c6_8mb_fromitems.build_flags}
framework = arduino
board = esp32-c6-devkitm-1
platform = espressif32 @6.9.0
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
monitor_filters = esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
board_build.partitions = tools/partitions_custom_8mb.csv
board_upload.flash_size = 8MB
board_build.filesystem = littlefs
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:esp32c6_8mb_fromitems.build_src_filter}

[env:bk7231n]
extra_scripts = 
	pre:tools/lt_fsbuild.py
	pre:tools/lt_fsflash.py
lib_compat_mode = off
lib_deps = 
	LT_WebSockets
	https://github.com/Mit4el/ESPAsyncUDP#master
	${common_env_data.lib_deps_external}
	${env:bk7231n_fromitems.lib_deps}
lib_ignore = EspSoftwareSerial, HTTPUpdate, WebSockets
platform = https://github.com/Mit4el/libretiny#master
framework = arduino
board = generic-bk7231n-qfn32-tuya
custom_fw_name = iotm_tiny
custom_fw_version = 0.0.1
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-Dbk7231n="bk7231n"
	-DLT_LOGLEVEL=LT_LEVEL_FATAL
	-DLT_DEBUG_ALL=1
	-DPROJECT_DATA_DIR="data_svelte"
	-DLT_USE_TIME=1
	-DDEBUG_ESP_PORT=Serial1
	-DNODEBUG_WEBSOCKETS=1
	-DLT_UART_DEFAULT_PORT=1
	-DUPLOAD_PORT=auto
	${env:bk7231n_fromitems.build_flags}
build_src_filter = 
	+<*.cpp>
	+<classes/*.cpp>
	+<utils/*.cpp>
	+<modules/*.cpp>
	${env:bk7231n_fromitems.build_src_filter}

[env:esp8266_1mb_ota_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp8266_1mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp8266_2mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp8266_2mb_ota_fromitems]
lib_deps = 
	adafruit/Adafruit BME280 Library
	plerup/EspSoftwareSerial
build_src_filter = 
	+<modules/virtual/Cron>
	+<modules/virtual/Loging>
	+<modules/virtual/LogingDaily>
	+<modules/virtual/Timer>
	+<modules/virtual/Variable>
	+<modules/virtual/VariableColor>
	+<modules/virtual/VButton>
	+<modules/sensors/Bme280>
	+<modules/sensors/Pzem004t>
	+<modules/sensors/UART>
	+<modules/exec/TelegramLT>

[env:esp8285_1mb_ota_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp8285_1mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp8266_4mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
	+<modules/exec/ButtonIn>
	+<modules/exec/ButtonOut>
build_flags = 

[env:esp32_4mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/virtual/Variable>
build_flags = 

[env:esp32_4mb3f_fromitems]
lib_deps = 
	https://github.com/enjoyneering/AHTxx.git
	adafruit/Adafruit BME280 Library
	adafruit/Adafruit BMP280 Library
	beegee-tokyo/DHT sensor library for ESPx
	milesburton/DallasTemperature @ ^4.0.4
	plerup/EspSoftwareSerial
	gyverlibs/EncButton @ ^2.0
build_src_filter = 
	+<modules/virtual/Cron>
	+<modules/virtual/Loging>
	+<modules/virtual/LogingDaily>
	+<modules/virtual/LogingHourly>
	+<modules/virtual/Math>
	+<modules/virtual/owmWeather>
	+<modules/virtual/Ping>
	+<modules/virtual/Timer>
	+<modules/virtual/UpdateServer>
	+<modules/virtual/Variable>
	+<modules/virtual/VButton>
	+<modules/sensors/AhtXX>
	+<modules/sensors/AnalogAdc>
	+<modules/sensors/Bme280>
	+<modules/sensors/Bmp280>
	+<modules/sensors/Dht1122>
	+<modules/sensors/Ds18b20>
	+<modules/sensors/Impulse>
	+<modules/sensors/Ntc>
	+<modules/sensors/RTC>
	+<modules/sensors/UART>
	+<modules/exec/AnalogBtn>
	+<modules/exec/ButtonIn>
	+<modules/exec/ButtonOut>
	+<modules/exec/Enconder>
	+<modules/exec/Multitouch>
	+<modules/exec/Pwm32>
	+<modules/exec/TelegramLT>
	+<modules/exec/Thermostat>
build_flags = 
	-Dmod_RtcDriver
	-DhardRTC=1

[env:esp32cam_4mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp32s2_4mb_fromitems]
lib_deps = 
	https://github.com/crankyoldgit/IRremoteESP8266
	gyverlibs/FastBot
	plerup/EspSoftwareSerial
	https://github.com/robotclass/RobotClass_LiquidCrystal_I2C
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	https://github.com/maxint-rd/TM16xx
	https://github.com/adafruit/Adafruit-GFX-Library
	adafruit/Adafruit BusIO @ ^1.13.2
	adafruit/Adafruit NeoPixel@^1.10.6
build_src_filter = 
	+<modules/exec/AnalogBtn>
	+<modules/exec/BrokerMQTT>
	+<modules/exec/Buzzer>
	+<modules/exec/Ftp>
	+<modules/exec/HttpGet>
	+<modules/exec/IRremote>
	+<modules/exec/Telegram_v2>
	+<modules/display/DwinI>
	+<modules/display/Lcd2004>
	+<modules/display/Smi2_m>
	+<modules/display/TM16XX>
	+<modules/display/Ws2812b>
build_flags = 
	

[env:esp8266_16mb_fromitems]
lib_deps = 
	https://github.com/dancol90/ESP8266Ping
	https://github.com/enjoyneering/AHTxx.git
	adafruit/Adafruit BME280 Library
	adafruit/Adafruit BMP280 Library
	beegee-tokyo/DHT sensor library for ESPx
	https://github.com/milesburton/Arduino-Temperature-Control-Library
	plerup/EspSoftwareSerial
	gyverlibs/EncButton @ ^2.0
build_src_filter = 
	+<modules/virtual/Cron>
	+<modules/virtual/Loging>
	+<modules/virtual/LogingDaily>
	+<modules/virtual/LogingHourly>
	+<modules/virtual/Math>
	+<modules/virtual/owmWeather>
	+<modules/virtual/Ping>
	+<modules/virtual/Timer>
	+<modules/virtual/UpdateServer>
	+<modules/virtual/Variable>
	+<modules/virtual/VButton>
	+<modules/sensors/AhtXX>
	+<modules/sensors/AnalogAdc>
	+<modules/sensors/Bme280>
	+<modules/sensors/Bmp280>
	+<modules/sensors/Dht1122>
	+<modules/sensors/Ds18b20>
	+<modules/sensors/Impulse>
	+<modules/sensors/Ntc>
	+<modules/sensors/RTC>
	+<modules/sensors/UART>
	+<modules/exec/AnalogBtn>
	+<modules/exec/ButtonIn>
	+<modules/exec/ButtonOut>
	+<modules/exec/Buzzer>
	+<modules/exec/Enconder>
	+<modules/exec/Multitouch>
	+<modules/exec/TelegramLT>
	+<modules/exec/Thermostat>

[env:esp32_16mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp32c3m_4mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/virtual/Cron>
	+<modules/virtual/Loging>
	+<modules/virtual/LogingDaily>
	+<modules/virtual/owmWeather>
	+<modules/virtual/Timer>
	+<modules/virtual/Variable>
	+<modules/virtual/VariableColor>
	+<modules/virtual/VButton>

[env:esp32s3_16mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/sensors/AnalogAdc>
build_flags = 

[env:esp32_wifirep_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:esp32c6_4mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/virtual/Variable>
build_flags = 

[env:esp32c6_8mb_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

[env:bk7231n_fromitems]
lib_deps = 
build_src_filter = 
	+<modules/exec/AnalogBtn>
build_flags = 

